### ISSUE TITLE
[RoleUtils] Add target args support to showing members with custom formatting string

### ISSUE THREAD

**Issue by NNTin** [phenom4n4n/phen-cogs#120]
In #89 you could do custom formatting. It's an awesome feature.

However as it is now it shows all members with a certain role using that custom formatting.
Another use case would be to show members with role A, B but without role C using that custom formatting scheme.

So instead of 

```
[p]role members @role {member(mention)}
```

It would be cool if you could do

```
[p]role members --roles @A @B --not-roles @C {member(mention)}
```

**Comment by phenom4n4n** [comment]
The `role dump` command is meant to be a quick method to view the members of the role. The suggested addition to use targeting args adds extra complexity to it. Additionally, the command would accept targeting for various args rather than just roles, which isn't apt for a roles related cog. The Targeter cog can already display users with mentions, and you should request its author to add support for custom formatted output of members.
