### ISSUE TITLE
[LinkQuoter] Feature Request : allow cross server links

### ISSUE THREAD

**Issue by thisisjvgrace** [phenom4n4n/phen-cogs#2]
hey,

nice nifty cog, thanks for that. 
currently linkquoter only quotes links if they're of the same server, but I think if it could quote cross server links, it would be useful for owners and mods who operate on multiple community servers utilizing the same bot. It could potentially save us time when sharing cross server links so we don't have to spend time giving context to other users who don't know where the direct message link originated from because bot will automatically provide the rough context. there could be other scenarios in which this feature would be helpful to community leaders, which I am not able to think right now.

**Comment by phenom4n4n** [comment]
Hello, 
When I originally wrote this cog I didn't want servers or users to be able to snoop on messages from servers/channels they can't read. I can implement this, but for privacy servers will have to opt-in to enable cross server quoting. I'm planning to do a rewrite this week.

**Comment by thisisjvgrace** [comment]
yeah that's a valid concern. opt in sounds like the best approach. thanks for answering.

**Comment by phenom4n4n** [comment]
Oops- sorry for this being late but I've completed a base rewrite of linkquoter in #5. I haven't finished testing it yet but you can help test by installing it by that branch and messing around. In the rewrite, it requires my webhook cog to be installed for webhook support since that cog has a new function other cogs can use that ultimately makes it much easier to implement webhooks without breaking. That cog also caches them allowing for webhook quotes to go faster. Bot owners can disable that cog while keeping it loaded for usage using Red's core commands.

**Comment by thisisjvgrace** [comment]
Thanks a bunch. I'll close this now.
